DELETE http://localhost:3001/api/blogs/64b3fe4f550e9a5b6c2d61e3
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6IkpvaG5ueSIsImlkIjoiNjRiM2Y3YjA5MzdkNTQxZDMyYTJmODc3IiwiaWF0IjoxNjg5NTE3NjI3LCJleHAiOjE2ODk1MjEyMjd9.9L3dXNWGHlycfrrshEUU2fb9FlKD_-0uvyIq5eYuZ6w
